# Generated by Django 4.0 on 2023-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0015_rename_socialmedia_committeemember_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='memberPhoto',
            field=models.ImageField(upload_to='member_photos/'),
        ),
    ]
