# Generated by Django 4.0 on 2023-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(choices=[('Software Cordinator', 'Software_Cordiantor'), ('Graphic Designer', 'Graphic_Dedigner'), ('Hardware Cordinator', 'Hardware_Cordiantor')], max_length=25)),
            ],
        ),
    ]
