# Generated by Django 4.0 on 2023-06-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intakeform',
            old_name='email',
            new_name='intake_email',
        ),
        migrations.RenameField(
            model_name='intakeform',
            old_name='name',
            new_name='intake_name',
        ),
        migrations.RenameField(
            model_name='intakeform',
            old_name='position',
            new_name='intake_position',
        ),
        migrations.RenameField(
            model_name='intakeform',
            old_name='rollno',
            new_name='intake_rollno',
        ),
    ]
