# Generated by Django 4.0 on 2023-06-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0003_intakeform_intake_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeform',
            name='intake_cv',
            field=models.FileField(upload_to='intake_cv/'),
        ),
    ]
