# Generated by Django 4.0 on 2023-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0005_intakeform_intake_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeform',
            name='intake_number',
            field=models.CharField(max_length=15),
        ),
    ]
