# Generated by Django 4.0 on 2023-06-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0007_rename_intake_number_intakeform_intake_phn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='intake_batch',
            field=models.CharField(choices=[('2076', '2076'), ('2077', '2077'), ('2078', '2078'), ('2079', '2079'), ('2080', '2080')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='intake_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='intake_faculty',
            field=models.CharField(choices=[('BCT', 'BCT'), ('BEI', 'BEI')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='intake_github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='intake_introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='intake_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='intake_opinion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='intake_position',
            field=models.CharField(choices=[('Communication_and_HR', 'Communication and HR'), ('Software_Cordinator', 'Software Cordiantor'), ('Graphic_Designer', 'Graphic Designer'), ('Hardware_Cordinator', 'Hardware Cordiantor'), ('Event_Manager', ' Event Manager'), ('Social_Media_Manager', 'Social Media Manager'), ('Research', 'Research'), ('General_Member', 'General Member')], max_length=25),
        ),
    ]
