# Generated by Django 4.0 on 2023-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0009_alter_intakeform_intake_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeform',
            name='intake_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
